#ifndef ESP32_LIGHT_FAKELIGHT_H
#define ESP32_LIGHT_FAKELIGHT_H

#define DEFAULT_DISPLAY_NAME "Fake Light"
#define DEFAULT_SERVICE_NAME "Elgato Key Light Air 1337"
#define DEFAULT_DEVICE_ID "3C:6A:9D:13:C1:BD"

#endif //ESP32_LIGHT_FAKELIGHT_H
